### ISSUE TITLE
Cannot read property Servicos of undefined

### ISSUE THREAD

**Issue by lucasbordini** [vitorleal/node-correios#27]
Estou tentando utilizar a biblioteca porém a mesma da o seguinte erro:

/Users/vntlura/Documents/Personal/Angular/CorreiosTeste/functions/node_modules/node-correios/lib/correios.js:104

callback ? callback(err, result.CalcPrecoPrazoResult.Servicos.cServico) : (!err ? resolve(result.CalcPrecoPrazoResult.Servicos.cServico) : reject(err)); 
                                                               ^

TypeError: Cannot read property 'Servicos' of undefined
    at /Users/vntlura/Documents/Personal/Angular/CorreiosTeste/functions/node_modules/node-correios/lib/correios.js:104:64
    at /Users/vntlura/Documents/Personal/Angular/CorreiosTeste/functions/node_modules/soap/lib/client.js:180:7
    at parseSync (/Users/vntlura/Documents/Personal/Angular/CorreiosTeste/functions/node_modules/soap/lib/client.js:371:14)
    at /Users/vntlura/Documents/Personal/Angular/CorreiosTeste/functions/node_modules/soap/lib/client.js:349:14
    at Request._callback (/Users/vntlura/Documents/Personal/Angular/CorreiosTeste/functions/node_modules/soap/lib/http.js:118:5)
    at Request.self.callback (/Users/vntlura/Documents/Personal/Angular/CorreiosTeste/functions/node_modules/request/request.js:198:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/Users/vntlura/Documents/Personal/Angular/CorreiosTeste/functions/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:194:15)`

é alguma coisa com a API dos correios, com o modulo ou eu estou fazendo alguma coisa errada ? minha chamada para a lib é feita da seguinda forma: 

```
app.post('/calc_frete', (req, response) => {
    const nCdServico = req.body.nCdServico;
    const sCepOrigem = req.body.sCepOrigem;
    const sCepDestino = req.body.sCepDestino;
    const nVlPeso = req.body.nVlPeso;
    const nCdFormato = req.body.nCdFormato;
    const nVlComprimento = req.body.nVlComprimento;
    const nVlAltura = req.body.nVlAltura;
    const nVlLargura = req.body.nVlLargura;
    const nVlDiametro = req.body.nVlDiametro;
    var args = {
        nCdServico: nCdServico,
        sCepOrigem: sCepOrigem,
        sCepDestino: sCepDestino,
        nVlPeso: nVlPeso,
        nCdFormato: nCdFormato,
        nVlComprimento: nVlComprimento,
        nVlAltura: nVlAltura,
        nVlLargura: nVlLargura,
        nVlDiametro: nVlDiametro
    }
    correios.calcPrecoPrazo(args, (err, res) => { 
       response.json(res[0]) 
    });
});
```

Obrigado.

**Comment by danielmelogpi** [comment]
Tambem tive o mesmo problema com essa biblioteca.

```
2019-05-13 15:33:05 ERROR       • superon  •       UNCAUGHT EXCEPTION  Cannot read property 'CalcPrecoPrazo' of undefined
2019-05-13 15:33:05 ERROR       • superon  •      [Inside 'uncaughtException' event] TypeError: Cannot read property 'CalcPrecoPrazo' of undefined
    at /Users/daniel/development/projects/superon-server/node_modules/node-correios/lib/correios.js:103:14
    at /Users/daniel/development/projects/superon-server/node_modules/soap/lib/soap.js:58:5
    at /Users/daniel/development/projects/superon-server/node_modules/soap/lib/soap.js:22:18
    at /Users/daniel/development/projects/superon-server/node_modules/soap/lib/wsdl.js:2204:9
    at Request._callback (/Users/daniel/development/projects/superon-server/node_modules/soap/lib/http.js:118:5)
    at Request.self.callback (/Users/daniel/development/projects/superon-server/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/daniel/development/projects/superon-server/node_modules/request/request.js:1060:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/daniel/development/projects/superon-server/node_modules/request/request.js:980:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
Waiting for the debugger to disconnect...
[1]    51761 killed     env SUPERON_UPLOADLOGO_PATH=/opt/superon/public/images/logos            

```

![image](https://user-images.githubusercontent.com/3124696/57645563-e939ce00-7594-11e9-84d2-e161272f47d7.png)

Essa é a resposta da api no breakpoint acima:

```
{
   "html":{
      "head":{
         "meta":{
            "attributes":{
               "http-equiv":"Content-Type",
               "content":"text/html; charset=iso-8859-1"
            }
         },
         "title":"403 - Forbidden: Access is denied.",
         "style":{
            "attributes":{
               "type":"text/css"
            }
         }
      },
      "body":{
         "div":[
            {
               "attributes":{
                  "id":"header"
               },
               "h1":"Server Error"
            },
            {
               "attributes":{
                  "id":"content"
               },
               "div":{
                  "attributes":{
                     "class":"content-container"
                  },
                  "fieldset":{
                     "h2":"403 - Forbidden: Access is denied.",
                     "h3":"You do not have permission to view this directory or page using the credentials that you supplied."
                  }
               }
            }
         ]
      }
   }
}
```
